# Generated by Django 4.1.1 on 2022-12-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phoneno', models.IntegerField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
