# Generated by Django 4.1.1 on 2022-12-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbancloud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='desc',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='phoneno',
            new_name='subject',
        ),
    ]
