# Generated by Django 4.1.1 on 2022-12-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbancloud', '0002_rename_desc_contactus_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
